name: Sync winget‑pkgs upstream
on:
  schedule:
    # 每6小时同步一次，UTC时间，按需修改
    - cron: '0 */6 * * *'
  workflow_dispatch: # 支持手动点按钮立即执行

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync upstream winget‑pkgs
        uses: wei/git-sync@v3
        with:
          source_repo: "microsoft/winget-pkgs"
          source_branch: "master"
          destination_repo: ${{ github.repository }}
          destination_branch: "master"
          github_token: ${{ secrets.GH_PAT }}
          sync_tags: false
          force_sync: true
