name: Sync winget‑pkgs upstream
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: repo-sync/sync-fork-action@master
        with:
          upstream_repository: microsoft/winget-pkgs
          target_repository: ${{ github.repository }}
          target_branch: master
          github_token: ${{ secrets.GH_PAT }}
          force: true
