jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 拉取当前仓库
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: 同步上游 microsoft/winget-pkgs
        run: |
          git remote add upstream https://github.com/microsoft/winget-pkgs.git
          git fetch upstream
          git checkout main
          git merge upstream/main --allow-unrelated-histories -X theirs
          git push origin main
